# Things that can be appled.
interface Appleable {
  # Returns a list users who have appled this appleable.
  appleGivers(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Order for connection.
    orderBy: AppleGiverOrder
  ): AppleGiverConnection!

  id: ID!

  # Can the viewer apple this appleable.
  viewerCanApple: Boolean!

  # Has the viewer appled this appleable.
  viewerHasAppled: Boolean!
}
