# Things that can be enrolled in.
interface Enrollable {
  id: ID!

  # Can the viewer enroll in this enrollable.
  viewerCanEnroll: Boolean!

  # Is the viewer enrolled in this enrollable.
  viewerIsEnrolled: Boolean!
}
