// Code generated by go-bindata.
// sources:
// interfaces/node.gql
// interfaces/uniform_resource_locatable.gql
// scalars/html.gql
// scalars/time.gql
// scalars/uri.gql
// schema.gql
// type/page_info.gql
// type/user.gql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _interfacesNodeGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xca\xcc\x2b\x49\x2d\x4a\x4b\x4c\x4e\x55\xf0\xcb\x4f\x49\x55\xa8\xe6\x52\x50\xc8\x4c\xb1\x52\xf0\x74\x51\xe4\xaa\xe5\x02\x04\x00\x00\xff\xff\x6f\x40\x52\x35\x1d\x00\x00\x00")

func interfacesNodeGqlBytes() ([]byte, error) {
	return bindataRead(
		_interfacesNodeGql,
		"interfaces/node.gql",
	)
}

func interfacesNodeGql() (*asset, error) {
	bytes, err := interfacesNodeGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "interfaces/node.gql", size: 29, mode: os.FileMode(420), modTime: time.Unix(1523374392, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _interfacesUniform_resource_locatableGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xcb\x41\xaa\x83\x30\x14\x85\xe1\x79\x56\x71\x1e\xce\x5d\xc0\x5b\x41\x0b\x0e\x24\x98\x05\x5c\xd3\x23\x09\xd8\x44\x6e\xae\x05\x29\xdd\x7b\x27\x52\x28\x74\xf6\x0f\xfe\xaf\x83\xe7\xa6\x6c\x2c\xd6\x20\xb0\x63\x23\x2c\x89\x21\x4a\xc1\x4c\x28\x4d\x33\x1f\xbc\x61\x3e\x20\x08\x7e\xe8\x5d\x2e\x46\x5d\x24\x12\xa1\xe4\xa5\xea\xdd\xb3\xd5\x5d\x23\x87\x1a\xc5\x64\x5e\x89\xa7\x03\x3a\x4c\x89\xb8\x4c\xd3\x88\x4d\x2c\xc1\x2a\x2c\xe5\x06\x3d\xef\xde\xe1\xd3\xa3\x58\xfa\x47\xf0\xd7\x3f\xf7\x2d\x83\x1f\x7e\xc2\x5d\xd7\xf3\x7f\xb9\x77\x00\x00\x00\xff\xff\xe9\x60\xa2\xe7\xc4\x00\x00\x00")

func interfacesUniform_resource_locatableGqlBytes() ([]byte, error) {
	return bindataRead(
		_interfacesUniform_resource_locatableGql,
		"interfaces/uniform_resource_locatable.gql",
	)
}

func interfacesUniform_resource_locatableGql() (*asset, error) {
	bytes, err := interfacesUniform_resource_locatableGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "interfaces/uniform_resource_locatable.gql", size: 196, mode: os.FileMode(420), modTime: time.Unix(1523803810, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsHtmlGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x70\x54\x28\x2e\x29\xca\xcc\x4b\x57\x48\xce\xcf\x2b\x49\xcc\xcc\x03\x31\x3d\x42\x7c\x7d\x14\x92\xf3\x53\x52\xf5\xb8\x8a\x93\x13\x73\x12\x8b\xc0\x22\x5c\x80\x00\x00\x00\xff\xff\x69\x83\x95\x22\x2d\x00\x00\x00")

func scalarsHtmlGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsHtmlGql,
		"scalars/html.gql",
	)
}

func scalarsHtmlGql() (*asset, error) {
	bytes, err := scalarsHtmlGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/html.gql", size: 45, mode: os.FileMode(420), modTime: time.Unix(1523745255, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsTimeGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x08\xc9\xcc\x4d\x55\xc8\x2c\x56\x48\xcc\x53\x08\x72\x73\x36\x36\x36\xb6\x54\x28\xc9\xcc\x4d\x2d\x2e\x49\xcc\x2d\xd0\xe3\x2a\x4e\x4e\xcc\x49\x2c\x02\x2b\xe2\x02\x04\x00\x00\xff\xff\x3c\x59\x30\xf9\x2c\x00\x00\x00")

func scalarsTimeGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsTimeGql,
		"scalars/time.gql",
	)
}

func scalarsTimeGql() (*asset, error) {
	bytes, err := scalarsTimeGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/time.gql", size: 44, mode: os.FileMode(420), modTime: time.Unix(1523805330, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsUriGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x70\xcc\x53\x08\x72\x73\x56\x30\xb6\xb4\x30\xd3\x81\xb1\xcc\x75\x14\x12\xf3\x52\xc0\x3c\x33\x53\x73\x03\x05\x8d\x9c\xd4\xb2\xd4\x1c\x05\x13\x4d\x85\xe4\xfc\xdc\x82\x9c\xcc\xc4\xbc\x12\x85\xd0\x20\x4f\x85\xe2\x92\xa2\xcc\xbc\x74\x3d\xae\xe2\xe4\xc4\x9c\xc4\x22\x90\x10\x17\x20\x00\x00\xff\xff\x12\xa3\x29\x58\x51\x00\x00\x00")

func scalarsUriGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsUriGql,
		"scalars/uri.gql",
	)
}

func scalarsUriGql() (*asset, error) {
	bytes, err := scalarsUriGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/uri.gql", size: 81, mode: os.FileMode(420), modTime: time.Unix(1523745591, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x8d\xbb\x8a\x84\x30\x14\x86\xfb\x3c\xc5\x9f\x2e\x82\x4f\x90\xda\xc6\x62\x17\x96\x65\x2b\xb1\x08\xe6\xe0\x06\x34\x71\x72\xe2\x88\x0c\xbe\xfb\x10\x2f\x03\xc3\x54\xe7\xf2\x5f\x3e\xee\xfe\x69\x34\x78\x08\xe0\x36\x53\x5c\x35\x7e\xf2\x10\xc0\x38\x27\x93\x5c\xf0\x1a\x5f\xe7\x26\x36\x91\xd6\x89\x0e\xc7\x1e\xf1\xc1\x92\x72\x56\xa3\xae\x64\xa1\xf1\x1d\x2c\x9d\x5f\x56\xce\xb2\x46\x53\x57\xb2\x2d\x34\x9a\x2c\xb5\x52\x00\x33\x53\x54\x43\xe8\x9d\xd7\xf8\x4d\xd1\xf9\x3e\x27\xff\x98\xa2\x00\xee\x8e\x16\x8a\xc7\x29\x2f\xdc\x85\xdf\x89\x5d\x24\x93\x28\xeb\x8a\x46\xe3\x86\x57\x49\x89\xf7\xd2\x12\x93\x61\x5e\x42\xb4\x1f\x9c\x4d\x3c\x03\x00\x00\xff\xff\xa4\xbb\x90\xec\xf6\x00\x00\x00")

func schemaGqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaGql,
		"schema.gql",
	)
}

func schemaGql() (*asset, error) {
	bytes, err := schemaGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema.gql", size: 246, mode: os.FileMode(420), modTime: time.Unix(1524088747, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _typePage_infoGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\xcf\xbd\x4a\xc7\x40\x10\x04\xf0\xfe\x9e\x62\xe4\xdf\x4a\x1e\x20\x8d\xa0\x95\x8d\x04\x2c\xac\x37\x97\xcd\xdd\xa1\xd9\x0d\x7b\x7b\x7e\x20\xbe\xbb\x9c\x82\x82\x44\xc4\x72\x77\x98\x1f\xcc\x09\xd7\xb2\xaa\x6d\xe4\x45\x05\x34\x6b\x73\xec\x94\x8a\x7c\x3e\x8a\x80\x10\x55\x84\x63\xbf\x87\xe0\x2f\x3b\x63\xa2\xc4\xbd\x86\xd7\x00\x9c\x70\x97\x59\xbe\x4a\x92\xb0\xaa\x3d\x91\x2d\xf5\x1c\x64\x0c\xcf\x6c\x8c\x4d\x8d\x51\x9c\xb7\x7a\x11\x80\x4c\xf5\x86\x9f\xbd\x3b\x23\x2e\x55\x1f\x98\xe4\x2c\x1c\x62\x33\xc5\xfb\xbf\xb5\xc9\xf8\xb1\x68\xab\xff\x14\x3d\x33\x62\xb3\xaa\x06\xd7\xbe\xd3\x8b\x34\x1e\x02\x50\x9d\xcc\xaf\x3e\xa2\x11\xb7\x6e\x45\xd2\xb1\xf6\x3d\xf6\x77\x8c\x65\xf9\x41\xbd\x85\xf7\x00\x00\x00\xff\xff\x92\xd2\xc8\xaf\x79\x01\x00\x00")

func typePage_infoGqlBytes() ([]byte, error) {
	return bindataRead(
		_typePage_infoGql,
		"type/page_info.gql",
	)
}

func typePage_infoGql() (*asset, error) {
	bytes, err := typePage_infoGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "type/page_info.gql", size: 377, mode: os.FileMode(420), modTime: time.Unix(1523742707, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _typeUserGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x92\x4f\x6b\x14\x41\x10\xc5\xef\xf3\x29\x9e\xe4\xe0\x45\xf2\x01\xe6\x16\x51\xc8\xc2\x2a\x61\x33\xab\xe7\xda\xe9\xda\x9d\x92\xfe\x33\x54\xd7\xb8\x04\xf1\xbb\x4b\xf5\x4e\x54\x12\x24\xc1\x53\x3f\x6a\xe6\xfd\xfa\x55\x75\x5d\x61\xc7\xb3\x72\xe5\x6c\x15\x84\xa5\xb2\x5e\x77\xf6\x30\x33\xf6\x95\x15\x92\xe6\xc8\xa9\x7d\xfc\x5c\x02\xbf\xc3\x3e\xcb\xb1\x68\xda\x71\x2d\x8b\x8e\xbc\x2d\x23\x19\x1d\x22\xe3\x47\x07\x5c\x61\x98\xb8\x31\xde\x56\xcc\xcb\x21\xca\x88\x59\xcb\x51\x22\xe3\x20\xe5\xba\x83\x1f\x3d\xee\x4d\x25\x9f\xba\x97\x1d\xa0\x8a\xdb\xe1\xd3\x76\x75\xba\xec\x5b\xe1\xcd\xc5\xbc\x09\x9c\x4d\x8e\xc2\x15\x36\x31\x02\x19\x83\x72\x80\x49\x62\x9c\x27\xce\xad\x5c\x0e\xdf\x78\x34\x9c\xa9\x62\x54\x26\xe3\xe0\xbc\x55\xde\x58\x8f\x41\x12\xbf\x94\x86\x13\x49\x74\x5f\x13\x7f\xf7\x20\xa1\xc7\xe6\xc3\x9a\xe8\xeb\xc4\x36\xb1\xa2\x28\x72\x31\xd8\x24\xb5\x01\x21\x3e\xde\x2a\x1e\x30\x24\xc9\x52\x4d\xc9\x8a\x3a\x51\xea\xbd\x18\xdf\x78\xb9\xc7\xfb\x52\x22\x53\x7e\x05\xce\x5b\xfb\x2e\x7c\x96\x7c\x5a\xdf\xcd\x51\x5f\x84\xcf\xac\x4f\x39\x8f\x7d\x65\x4a\x4d\x04\x58\x41\x2c\x27\xc9\xee\x6a\xe2\xb5\xcf\xe2\x08\x37\xf9\xf9\x6f\x8f\x4a\x22\x7d\xb8\x0c\xeb\xf7\x85\x55\x4e\x19\xcb\xec\xee\xf5\x87\x8f\x4f\x87\x79\xa1\xdc\x0e\xc3\x1d\x66\xb2\x09\xc7\xa2\x7f\xba\x76\xa3\xae\x9b\x77\x47\x36\xf5\xd8\xef\x36\xff\xbb\x0a\x91\xaa\x61\x99\xc3\xe3\x3e\xac\xf2\xf9\x3e\xb4\x30\xfb\xdd\xf6\x79\x96\x45\xe3\x1a\xe1\x67\xf7\x2b\x00\x00\xff\xff\x38\x6c\xbf\x74\x49\x03\x00\x00")

func typeUserGqlBytes() ([]byte, error) {
	return bindataRead(
		_typeUserGql,
		"type/user.gql",
	)
}

func typeUserGql() (*asset, error) {
	bytes, err := typeUserGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "type/user.gql", size: 841, mode: os.FileMode(420), modTime: time.Unix(1524683407, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"interfaces/node.gql": interfacesNodeGql,
	"interfaces/uniform_resource_locatable.gql": interfacesUniform_resource_locatableGql,
	"scalars/html.gql": scalarsHtmlGql,
	"scalars/time.gql": scalarsTimeGql,
	"scalars/uri.gql": scalarsUriGql,
	"schema.gql": schemaGql,
	"type/page_info.gql": typePage_infoGql,
	"type/user.gql": typeUserGql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"interfaces": &bintree{nil, map[string]*bintree{
		"node.gql": &bintree{interfacesNodeGql, map[string]*bintree{}},
		"uniform_resource_locatable.gql": &bintree{interfacesUniform_resource_locatableGql, map[string]*bintree{}},
	}},
	"scalars": &bintree{nil, map[string]*bintree{
		"html.gql": &bintree{scalarsHtmlGql, map[string]*bintree{}},
		"time.gql": &bintree{scalarsTimeGql, map[string]*bintree{}},
		"uri.gql": &bintree{scalarsUriGql, map[string]*bintree{}},
	}},
	"schema.gql": &bintree{schemaGql, map[string]*bintree{}},
	"type": &bintree{nil, map[string]*bintree{
		"page_info.gql": &bintree{typePage_infoGql, map[string]*bintree{}},
		"user.gql": &bintree{typeUserGql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

