// Code generated by go-bindata.
// sources:
// input/createUser.gql
// input/deleteUser.gql
// input/updateUser.gql
// interfaces/node.gql
// interfaces/uniform_resource_locatable.gql
// scalars/html.gql
// scalars/time.gql
// scalars/uri.gql
// schema.gql
// type/page_info.gql
// type/user.gql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _inputCreateuserGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xf0\xcc\x2b\x28\x2d\x51\x28\xa9\x2c\x48\x55\x48\xcb\x2f\x52\x70\x2e\x4a\x4d\x2c\x49\x0d\x2d\x4e\x2d\xe2\xca\x04\xcb\x20\x04\x20\x2a\xab\xb9\x14\x14\x52\x73\x13\x33\x73\xac\x14\x82\x4b\x8a\x32\xf3\xd2\x15\xb9\x14\x14\x72\xf2\xd3\x33\xf3\x90\x05\x0a\x12\x8b\x8b\xcb\xf3\x8b\x52\x10\x62\xb5\x5c\x80\x00\x00\x00\xff\xff\xd8\xd3\xc9\xe7\x6c\x00\x00\x00")

func inputCreateuserGqlBytes() ([]byte, error) {
	return bindataRead(
		_inputCreateuserGql,
		"input/createUser.gql",
	)
}

func inputCreateuserGql() (*asset, error) {
	bytes, err := inputCreateuserGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "input/createUser.gql", size: 108, mode: os.FileMode(420), modTime: time.Unix(1524840570, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _inputDeleteuserGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xf0\xcc\x2b\x28\x2d\x51\x28\xa9\x2c\x48\x55\x48\xcb\x2f\x52\x70\x49\xcd\x49\x2d\x49\x0d\x2d\x4e\x2d\xe2\xca\x04\xcb\x20\x04\x20\x2a\xab\xb9\x14\x14\x32\x53\xac\x14\x82\x4b\x8a\x32\xf3\xd2\x15\xb9\x6a\xb9\x00\x01\x00\x00\xff\xff\x44\x88\x7f\x07\x44\x00\x00\x00")

func inputDeleteuserGqlBytes() ([]byte, error) {
	return bindataRead(
		_inputDeleteuserGql,
		"input/deleteUser.gql",
	)
}

func inputDeleteuserGql() (*asset, error) {
	bytes, err := inputDeleteuserGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "input/deleteUser.gql", size: 68, mode: os.FileMode(420), modTime: time.Unix(1525442245, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _inputUpdateuserGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\xf0\xcc\x2b\x28\x2d\x51\x28\xa9\x2c\x48\x55\x48\xcb\x2f\x52\x08\x2d\x48\x49\x2c\x49\x0d\x2d\x4e\x2d\xe2\xca\x04\xcb\x20\x04\x20\x2a\xab\xb9\x14\x14\x92\x32\xf3\xad\x14\xe0\x20\xb8\xa4\x28\x33\x2f\x9d\x4b\x41\x21\x33\x05\x49\x14\x2a\xac\xc8\xa5\xa0\x90\x93\x9f\x9e\x99\x67\x85\xa1\x3c\x2f\x31\x37\xd5\x0a\xdd\x94\x5a\x2e\x40\x00\x00\x00\xff\xff\x24\xd3\x8d\x9e\x93\x00\x00\x00")

func inputUpdateuserGqlBytes() ([]byte, error) {
	return bindataRead(
		_inputUpdateuserGql,
		"input/updateUser.gql",
	)
}

func inputUpdateuserGql() (*asset, error) {
	bytes, err := inputUpdateuserGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "input/updateUser.gql", size: 147, mode: os.FileMode(420), modTime: time.Unix(1525462700, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _interfacesNodeGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xca\xcc\x2b\x49\x2d\x4a\x4b\x4c\x4e\x55\xf0\xcb\x4f\x49\x55\xa8\xe6\x52\x50\xc8\x4c\xb1\x52\xf0\x74\x51\xe4\xaa\xe5\x02\x04\x00\x00\xff\xff\x6f\x40\x52\x35\x1d\x00\x00\x00")

func interfacesNodeGqlBytes() ([]byte, error) {
	return bindataRead(
		_interfacesNodeGql,
		"interfaces/node.gql",
	)
}

func interfacesNodeGql() (*asset, error) {
	bytes, err := interfacesNodeGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "interfaces/node.gql", size: 29, mode: os.FileMode(420), modTime: time.Unix(1523374392, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _interfacesUniform_resource_locatableGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xcb\x41\xaa\x83\x30\x14\x85\xe1\x79\x56\x71\x1e\xce\x5d\xc0\x5b\x41\x0b\x0e\x24\x98\x05\x5c\xd3\x23\x09\xd8\x44\x6e\xae\x05\x29\xdd\x7b\x27\x52\x28\x74\xf6\x0f\xfe\xaf\x83\xe7\xa6\x6c\x2c\xd6\x20\xb0\x63\x23\x2c\x89\x21\x4a\xc1\x4c\x28\x4d\x33\x1f\xbc\x61\x3e\x20\x08\x7e\xe8\x5d\x2e\x46\x5d\x24\x12\xa1\xe4\xa5\xea\xdd\xb3\xd5\x5d\x23\x87\x1a\xc5\x64\x5e\x89\xa7\x03\x3a\x4c\x89\xb8\x4c\xd3\x88\x4d\x2c\xc1\x2a\x2c\xe5\x06\x3d\xef\xde\xe1\xd3\xa3\x58\xfa\x47\xf0\xd7\x3f\xf7\x2d\x83\x1f\x7e\xc2\x5d\xd7\xf3\x7f\xb9\x77\x00\x00\x00\xff\xff\xe9\x60\xa2\xe7\xc4\x00\x00\x00")

func interfacesUniform_resource_locatableGqlBytes() ([]byte, error) {
	return bindataRead(
		_interfacesUniform_resource_locatableGql,
		"interfaces/uniform_resource_locatable.gql",
	)
}

func interfacesUniform_resource_locatableGql() (*asset, error) {
	bytes, err := interfacesUniform_resource_locatableGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "interfaces/uniform_resource_locatable.gql", size: 196, mode: os.FileMode(420), modTime: time.Unix(1523803810, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsHtmlGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x70\x54\x28\x2e\x29\xca\xcc\x4b\x57\x48\xce\xcf\x2b\x49\xcc\xcc\x03\x31\x3d\x42\x7c\x7d\x14\x92\xf3\x53\x52\xf5\xb8\x8a\x93\x13\x73\x12\x8b\xc0\x22\x5c\x80\x00\x00\x00\xff\xff\x69\x83\x95\x22\x2d\x00\x00\x00")

func scalarsHtmlGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsHtmlGql,
		"scalars/html.gql",
	)
}

func scalarsHtmlGql() (*asset, error) {
	bytes, err := scalarsHtmlGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/html.gql", size: 45, mode: os.FileMode(420), modTime: time.Unix(1523745255, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsTimeGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x08\xc9\xcc\x4d\x55\xc8\x2c\x56\x48\xcc\x53\x08\x72\x73\x36\x36\x36\xb6\x54\x28\xc9\xcc\x4d\x2d\x2e\x49\xcc\x2d\xd0\xe3\x2a\x4e\x4e\xcc\x49\x2c\x02\x2b\xe2\x02\x04\x00\x00\xff\xff\x3c\x59\x30\xf9\x2c\x00\x00\x00")

func scalarsTimeGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsTimeGql,
		"scalars/time.gql",
	)
}

func scalarsTimeGql() (*asset, error) {
	bytes, err := scalarsTimeGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/time.gql", size: 44, mode: os.FileMode(420), modTime: time.Unix(1523805330, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scalarsUriGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x56\x70\xcc\x53\x08\x72\x73\x56\x30\xb6\xb4\x30\xd3\x81\xb1\xcc\x75\x14\x12\xf3\x52\xc0\x3c\x33\x53\x73\x03\x05\x8d\x9c\xd4\xb2\xd4\x1c\x05\x13\x4d\x85\xe4\xfc\xdc\x82\x9c\xcc\xc4\xbc\x12\x85\xd0\x20\x4f\x85\xe2\x92\xa2\xcc\xbc\x74\x3d\xae\xe2\xe4\xc4\x9c\xc4\x22\x90\x10\x17\x20\x00\x00\xff\xff\x12\xa3\x29\x58\x51\x00\x00\x00")

func scalarsUriGqlBytes() ([]byte, error) {
	return bindataRead(
		_scalarsUriGql,
		"scalars/uri.gql",
	)
}

func scalarsUriGql() (*asset, error) {
	bytes, err := scalarsUriGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scalars/uri.gql", size: 81, mode: os.FileMode(420), modTime: time.Unix(1523745591, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x5c\x8e\x3b\x6e\x84\x30\x18\x84\x7b\x9f\x62\xdc\x39\x57\x70\x1b\x1a\x8a\x44\x8a\x22\x2a\x44\x81\xf0\x2f\x62\x09\x6c\xe2\x47\x22\xb4\xda\xbb\xaf\x7e\x1e\xd6\xb2\x95\xed\x6f\xc6\x33\x13\x87\x1f\x9a\x7b\xdc\x04\xf0\x9b\x29\xac\x1a\x5f\x7c\x08\x60\xce\xa9\x4f\xd6\x3b\x8d\x8f\xe3\x26\xee\x22\xad\x0b\xed\x8e\xed\x8b\xf3\x86\x94\x35\x1a\x75\x25\xdf\x34\x3e\xbd\xa1\x83\x46\x65\x4d\xd4\x68\xeb\x4a\x76\x2c\xb5\xac\x75\x52\x00\x39\x52\x50\x93\x1f\xad\xd3\xf8\x4e\xc1\xba\x91\xf5\x26\x52\x10\xc0\x9f\xa5\x7f\x0a\xfb\x53\x9e\x7d\x67\xff\x56\x39\x04\xea\x13\xb1\xae\xac\x5b\x72\xd2\x78\x2f\xa4\x66\xf0\x94\x66\x68\xa2\xab\xb7\x2a\xa4\x78\xf7\x0d\x3c\x6c\x31\x2f\xc9\x4d\x21\x97\x64\x1e\xf6\x08\x00\x00\xff\xff\x89\x73\x5f\xde\x38\x01\x00\x00")

func schemaGqlBytes() ([]byte, error) {
	return bindataRead(
		_schemaGql,
		"schema.gql",
	)
}

func schemaGql() (*asset, error) {
	bytes, err := schemaGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema.gql", size: 312, mode: os.FileMode(420), modTime: time.Unix(1525442632, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _typePage_infoGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\xcf\xbd\x4a\xc7\x40\x10\x04\xf0\xfe\x9e\x62\xe4\xdf\x4a\x1e\x20\x8d\xa0\x95\x8d\x04\x2c\xac\x37\x97\xcd\xdd\xa1\xd9\x0d\x7b\x7b\x7e\x20\xbe\xbb\x9c\x82\x82\x44\xc4\x72\x77\x98\x1f\xcc\x09\xd7\xb2\xaa\x6d\xe4\x45\x05\x34\x6b\x73\xec\x94\x8a\x7c\x3e\x8a\x80\x10\x55\x84\x63\xbf\x87\xe0\x2f\x3b\x63\xa2\xc4\xbd\x86\xd7\x00\x9c\x70\x97\x59\xbe\x4a\x92\xb0\xaa\x3d\x91\x2d\xf5\x1c\x64\x0c\xcf\x6c\x8c\x4d\x8d\x51\x9c\xb7\x7a\x11\x80\x4c\xf5\x86\x9f\xbd\x3b\x23\x2e\x55\x1f\x98\xe4\x2c\x1c\x62\x33\xc5\xfb\xbf\xb5\xc9\xf8\xb1\x68\xab\xff\x14\x3d\x33\x62\xb3\xaa\x06\xd7\xbe\xd3\x8b\x34\x1e\x02\x50\x9d\xcc\xaf\x3e\xa2\x11\xb7\x6e\x45\xd2\xb1\xf6\x3d\xf6\x77\x8c\x65\xf9\x41\xbd\x85\xf7\x00\x00\x00\xff\xff\x92\xd2\xc8\xaf\x79\x01\x00\x00")

func typePage_infoGqlBytes() ([]byte, error) {
	return bindataRead(
		_typePage_infoGql,
		"type/page_info.gql",
	)
}

func typePage_infoGql() (*asset, error) {
	bytes, err := typePage_infoGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "type/page_info.gql", size: 377, mode: os.FileMode(420), modTime: time.Unix(1523742707, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _typeUserGql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x92\x4f\x8b\xd4\x40\x10\xc5\xef\xf9\x14\x4f\xf6\xe0\x45\xf6\x03\xe4\xb6\xe2\x61\x07\x46\x59\xb2\x89\x9e\x3b\xe9\xca\x74\x49\xff\x09\xd5\x15\x83\x88\xdf\x5d\xba\xe9\x45\xd4\x85\x19\x3c\xd5\xa3\xc2\xfb\xf1\x2a\xaf\xef\x30\xd0\x26\x94\x29\x6a\x86\xc1\x9e\x49\xee\x3b\xfd\xbe\x11\xa6\x4c\x02\x0e\x9b\xa7\x50\x3f\x7e\x4a\x96\xde\x61\x8a\xbc\x26\x09\x03\xe5\xb4\xcb\x42\xe7\xb4\x18\x35\xb3\x27\xfc\xe8\x80\x3b\x8c\x8e\x2a\xe3\x6d\xc6\xb6\xcf\x9e\x17\x6c\x92\x56\xf6\x84\x99\xd3\x7d\x87\x32\x7a\x3c\xab\x70\xbc\xbc\xe9\xae\x5b\x60\x32\x1e\xc7\x8f\xe7\x66\x2d\xb2\xaf\x8b\x66\x3e\x59\x8a\xca\x2b\x53\x86\x3a\x82\x35\x4a\x30\xd1\x42\x39\x10\x0e\x47\xb1\xae\xd3\xfc\x95\x16\xc5\x61\x32\x16\x21\xa3\x64\x0b\xaf\xc9\x07\xed\x31\x72\xa0\xab\x71\x28\x18\xf6\xc5\x58\xc5\x1f\x57\xb0\xed\x71\xfa\xd0\x08\x5f\x1c\xa9\x23\x41\x12\xc4\xa4\x50\xc7\xb9\x12\xc1\xe5\x0f\x67\x2e\x11\x6d\xe0\xc8\x59\xc5\x68\x92\x82\xe4\xfc\xcc\x4a\x0f\x65\xdd\xe3\x7d\x4a\x9e\x4c\xbc\x01\x57\x8e\xfb\xc6\x74\x70\xbc\xb4\xea\x0a\xea\x33\xd3\x41\xf2\x37\xe7\xe5\xb0\x68\x42\x15\x16\x9a\xe0\xd3\x85\x63\x71\x55\x71\x73\x33\x85\x51\x5c\x65\xbe\x62\x7a\x1c\xc7\x27\x6c\x46\x1d\xd6\x24\xbf\x13\x17\x87\xb4\x87\xf3\x64\xd4\xf5\x98\x86\xd3\xff\x16\xe9\x4d\x56\xec\x9b\x7d\x69\xb3\xc9\x57\xda\xac\x69\xa6\xe1\xfc\x6f\x98\x5d\x7c\xcb\xf0\xb3\xfb\x15\x00\x00\xff\xff\x8a\xcc\xcf\x55\x09\x03\x00\x00")

func typeUserGqlBytes() ([]byte, error) {
	return bindataRead(
		_typeUserGql,
		"type/user.gql",
	)
}

func typeUserGql() (*asset, error) {
	bytes, err := typeUserGqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "type/user.gql", size: 777, mode: os.FileMode(420), modTime: time.Unix(1525462513, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"input/createUser.gql": inputCreateuserGql,
	"input/deleteUser.gql": inputDeleteuserGql,
	"input/updateUser.gql": inputUpdateuserGql,
	"interfaces/node.gql": interfacesNodeGql,
	"interfaces/uniform_resource_locatable.gql": interfacesUniform_resource_locatableGql,
	"scalars/html.gql": scalarsHtmlGql,
	"scalars/time.gql": scalarsTimeGql,
	"scalars/uri.gql": scalarsUriGql,
	"schema.gql": schemaGql,
	"type/page_info.gql": typePage_infoGql,
	"type/user.gql": typeUserGql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"input": &bintree{nil, map[string]*bintree{
		"createUser.gql": &bintree{inputCreateuserGql, map[string]*bintree{}},
		"deleteUser.gql": &bintree{inputDeleteuserGql, map[string]*bintree{}},
		"updateUser.gql": &bintree{inputUpdateuserGql, map[string]*bintree{}},
	}},
	"interfaces": &bintree{nil, map[string]*bintree{
		"node.gql": &bintree{interfacesNodeGql, map[string]*bintree{}},
		"uniform_resource_locatable.gql": &bintree{interfacesUniform_resource_locatableGql, map[string]*bintree{}},
	}},
	"scalars": &bintree{nil, map[string]*bintree{
		"html.gql": &bintree{scalarsHtmlGql, map[string]*bintree{}},
		"time.gql": &bintree{scalarsTimeGql, map[string]*bintree{}},
		"uri.gql": &bintree{scalarsUriGql, map[string]*bintree{}},
	}},
	"schema.gql": &bintree{schemaGql, map[string]*bintree{}},
	"type": &bintree{nil, map[string]*bintree{
		"page_info.gql": &bintree{typePage_infoGql, map[string]*bintree{}},
		"user.gql": &bintree{typeUserGql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

