schema {
  query: Query
  mutation: Mutation
}
type Query {
  node(id: ID!): Node
  nodes(ids: [ID!]!): [Node]!
  user(login: String!): User
  viewer: User!
}
type Mutation {
  createLesson(input: CreateLessonInput!): Lesson
  # deleteLesson(input: DeleteLessonInput!): Boolean!
  # updateLesson(input: UpdateLessonInput!): Lesson!
  createStudy(input: CreateStudyInput!): Study
  # deleteStudy(input: DeleteStudyInput!): Boolean!
  # updateStudy(input: UpdateStudyInput!): Study!
  createUser(input: CreateUserInput!): User
  deleteUser(input: DeleteUserInput!): String
  updateUser(input: UpdateUserInput!): User!
}
