schema {
  query: Query
  mutation: Mutation
}
type Query {
  node(id: ID!): Node
  nodes(ids: [ID!]): [Node]!
  user(login: String!): User
  viewer: User!
}
type Mutation {
  createUser(email: String!, login: String!, password: String!): User
}
