[app]
name = "api.rkus.ninja"

[aws]
region = "us-east-1"
upload_bucket = "markus-ninja-test-user-asset-us-east-1"

[db]
host = "localhost"
port = 5432
name = "markusninja_test"
user = "markus"
password = "fender917"

[smtp]
host = "smtp.example.com"
port = "587"
from_address = "noreply@rkus.ninja"
root_url = "http://localhost:3000"
user = "noreply@rkus.ninja"
password = "secret"
