[app]
name = "api.rkus.ninja"

[db]
host = "localhost"
port = 5432
name = "markusninja"
user = "markus"
password = "fender917"

[smtp]
host = "email-smtp.us-east-1.amazonaws.com"
port = "587"
from_address = "noreply@rkus.ninja"
root_url = "http://localhost:3000"
user = "AKIAJAKGPARBNEWK7RTA"
password = "AgqJhceQBXmjsDxBOPsctSpRO8kWk2HCGPsBLNvnjmL0"
