# Ways in which activities can be ordered upon return.
input ActivityOrder {
  # The direction in which to order activities by the specified field.
  direction: OrderDirection!

  # The field in which to order activities by.
  field: ActivityOrderField!
}
