# Ways in which apple giver connections can be ordered.
input AppleGiverOrder {
  # The direction in which to order nodes.
  direction: OrderDirection!

  # The field in which to order nodes by.
  field: AppleGiverOrderField!
}
