# Ways in which commentables can be ordered upon return.
input CommentableOrder {
  # The direction in which to order items by the specified field.
  direction: OrderDirection!

  # The field in which to order items by.
  field: CommentableOrderField!
}
