# Ways in which comments can be ordered upon return.
input CommentOrder {
  # The direction in which to order comments by the specified field.
  direction: OrderDirection!

  # The field in which to order comments by.
  field: CommentOrderField!
}
