# Ways in which courses can be ordered upon return.
input CourseOrder {
  # The direction in which to order courses by the specified field.
  direction: OrderDirection!

  # The field in which to order courses by.
  field: CourseOrderField!
}
