# Input type for CreateUserAsset.
input CreateUserAssetInput {
  # The ID of the asset.
  assetId: ID!

  # The description of the asset.
  description: String

  # The name of the asset.
  name: String!

  # The ID of the study.
  studyId: ID!
}
