# Ways in which enrollee connections can be ordered.
input EnrolleeOrder {
  # The direction in which to order nodes.
  direction: OrderDirection!

  # The field in which to order nodes by.
  field: EnrolleeOrderField!
}
