# Ways in which enrollables can be ordered upon return.
input EnrollableOrder {
  # The direction in which to order items by the specified field.
  direction: OrderDirection!

  # The field in which to order items by.
  field: EnrollableOrderField!
}
