# Ways in which events can be ordered upon return.
input EventOrder {
  # The direction in which to order events by the specified field.
  direction: OrderDirection!

  # The field in which to order events by.
  field: EventOrderField!
}
