# Ways in which following connections can be ordered.
input FollowingOrder {
  # The direction in which to order nodes.
  direction: OrderDirection!

  # The field in which to order nodes by.
  field: FollowingOrderField!
}
