# Ways in which lessons can be ordered upon return.
input LessonOrder {
  # The direction in which to order lessons by the specified field.
  direction: OrderDirection!

  # The field in which to order lessons by.
  field: LessonOrderField!
}
