# Ways in which searches can be ordered upon return.
input SearchOrder {
  # The direction in which to order items by the specified field.
  direction: OrderDirection!

  # The field in which to order items by.
  field: SearchOrderField!
}
