# Ways in which student connections can be ordered.
input StudentOrder {
  # The direction in which to order nodes.
  direction: OrderDirection!

  # The field in which to order nodes by.
  field: StudentOrderField!
}
