# Ways in which topics can be ordered upon return.
input TopicOrder {
  # The direction in which to order topics by the specified field.
  direction: OrderDirection!

  # The field in which to order topics by.
  field: TopicOrderField!
}
