# Input type for UpdateLesson.
input UpdateLessonInput {
  # The body of the lesson.
  body: String

  # ID of the lesson.
  lessonId: ID!

  # Identifies the lesson number.
  number: Int

  # The title of the lesson.
  title: String
}
