# Input type for UpdateUser.
input UpdateUserInput {
  # The user's public profile bio.
  bio: String

  # The username used to login.
  login: String

  # The user's public profile name.
  name: String

  # The user's public profile email.
  publicEmail: String

  # ID of the user.
  userId: String!
}
