# Ways in which users can be ordered upon return.
input UserOrder {
  # The direction in which to order users by the specified field.
  direction: OrderDirection!

  # The field in which to order users by.
  field: UserOrderField!
}
