# The possible states of an enrollment.
enum EnrollmentStatus {
  # The User is notified of all conversations.
  ENROLLED
  
  # The User is never notified.
  IGNORED

  # The User is notified only when participating or @mentioned.
  UNENROLLED
}
