# Properties by which search result item connections can be ordered.
enum SearchOrderField {
  # Order items by advance time.
  ADVANCED_AT

  # Order items by best match to query.
  BEST_MATCH

  # Order items by creation time.
  CREATED_AT

  # Order items by number.
  NUMBER

  # Order items by name.
  NAME

  # Order items by update time.
  UPDATED_AT
}
