# Represents the individual results of a search.
enum SearchType {
  # Returns results matching courses in studies.
  COURSE

  # Returns results matching labels in studies.
  LABEL

  # Returns results matching lessons in studies.
  LESSON

  # Returns results matching studies.
  STUDY

  # Returns results matching topics.
  TOPIC

  # Returns results matching users on rkus.ninja.
  USER

  # Returns results matching user assets on rkus.ninja.
  USER_ASSET
}
