# Properties by which asset connections can be ordered.
enum UserAssetOrderField {
  # Order assets by their number within an activity.
  ACTIVITY_NUMBER

  # Order assets by creation time.
  CREATED_AT

  # Order assets by name.
  NAME

  # Order assets by update time.
  UPDATED_AT
}
