# Output type for AddLessonComment.
type AddLessonCommentOutput {
  # The edge from the lesson's comment connection.
  commentEdge: LessonCommentEdge!

  # The lesson commented on.
  lesson: Lesson!
}
