# An edge type for Study.
type AppledStudyEdge implements Edge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Study!

  # When was the item appled?
  appledAt: Time!
}

# A connection type for Study.
type AppledStudyConnection implements Connection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [AppledStudyEdge]

  # A list of nodes.
  nodes: [Study]

  # The total count of items in the connection.
  totalCount: Int!
}
