# Represents a 'appled' event on a given appleable.
type AppledEvent implements 
  UserActivityEvent,
  Node
{
  # The appleable assocated with this 'appled' event.
  appleable: Appleable!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The study from which the event occurred.
  study: Study!

  # The user who performed the event.
  user: User!
}
