# Represents an appled event on a given subject.
type AppledEvent implements 
  UniformResourceLocatable,
  UserActivityEvent,
  Node
{
  # The appleable assocated with this `appled` event.
  appleable: Appleable!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The HTTP path to this resource.
  resourcePath: URI!

  # The HTTP URL to this resource.
  url: URI!

  # The user who performed the event.
  user: User!
}
