# Represents a commented event on a given subject.
type CommentedEvent implements 
  LessonTimelineEvent,
  NotificationEvent,
  Node,
  UserAssetTimelineEvent
{
  # The comment assocated with this `commented` event.
  comment: Comment!

  # The commentable associated with this `commented` event.
  commentable: Commentable!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The HTTP path to this resource.
  resourcePath: URI!

  # The HTTP URL to this resource.
  url: URI!

  # The user who performed the event.
  user: User!
}
