# Represents an created event on a given subject.
type CreatedEvent implements 
  NotificationEvent,
  UserActivityEvent,
  Node
{
  # The createable assocated with this `created` event.
  createable: Createable!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The HTTP path to this resource.
  resourcePath: URI!

  # The HTTP URL to this resource.
  url: URI!

  # The user who performed the event.
  user: User!
}
