# Return type for DeleteLessonComment.
type DeleteLessonCommentPayload {
  # The deleted lesson id.
  deletedLessonCommentId: ID!

  # The ID of the edge from the lesson's timeline connection.
  deletedLessonTimelineEdgeId: ID!

  # The lesson the deleted lesson comment was for.
  lesson: Lesson!
}
