# Represents an email verification token.
type EVT implements Token {
  # Identifies the date and time when the token was issued.
  issuedAt: Time!

  # Identifies the date and time when the token expires.
  expiresAt: Time!
}
