# Represents an email.
type Email implements Node {
  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The string value of the email. 
  value: String!
}
