# An edge in a labelable connection.
type LabelableEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Labelable

  # When was the item labeled in?
  labeledAt: Time!
}

# A list of labelables.
type LabelableConnection {
  # A list of edges.
  edges: [LabelableEdge]

  # The number of lessons associated with the label.
  lessonCount: Int!

  # The number of lesson comments associated with the label.
  lessonCommentCount: Int!

  # A list of nodes.
  nodes: [Labelable]

  # Information to aid in pagination.
  pageInfo: PageInfo!
}
