# Represents a lesson comment draft backup.
type LessonCommentDraftBackup {
  # Identifies the date and time when the object was created.
  createdAt: Time!

  # The lesson comment's backup draft.
  draft: String!

  id: ID!

  # The lesson comment associated with this draft backup.
  lessonComment: LessonComment!

  # Identifies the date and time when the object was last updated.
  updatedAt: Time!
}
