# An edge type for LessonTimelineEvent.
type LessonTimelineEventEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The event at the end of the edge.
  node: LessonTimelineEvent
}

# A connection type for LessonTimelineEvent.
type LessonTimelineConnection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [LessonTimelineEventEdge]

  # A list of nodes.
  nodes: [LessonTimelineEvent]

  # The total count of items in the connection.
  totalCount: Int!
}
