# Represents a lesson.
type Lesson implements 
  Commentable,
  Createable,
  Enrollable,
  Labelable,
  Node,
  Referenceable,
  Searchable,
  StudyNode,
  UniformResourceLocatable,
  Updateable
{
  # The user who authored this lesson. 
  author: User

  # The lesson body as Markdown.
  body: String!

  # The lesson body rendered to HTML.
  bodyHTML: HTML!

  # The lesson body rendered to text.
  bodyText: String!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  # Returns a list of comments for the current lesson.
  comments(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Ordering options for comments returned from the connection.
    orderBy: LessonCommentOrder
  ): LessonCommentConnection!

  # The course associated with the lesson, if any.
  course: Course

  # Identifies the lesson's number within its associated course, if any.
  courseNumber: Int

  # The current draft of changes for the lesson body as Markdown.
  draft: String!

  # Returns a list users who have enrolled in this enrollable.
  enrollees(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Filtering options for users returned from the connection.
    filterBy: UserFilters

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Order for connection.
    orderBy: EnrolleeOrder
  ): EnrolleeConnection!

  # Is the viewer dismissed, enrolled, or ignoring this enrollable.
  enrollmentStatus: EnrollmentStatus!

  id: ID!

  # Is this lesson part of a course?
  isCourseLesson: Boolean!

  # Returns a list of labels for the current lesson.
  labels(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Filtering options for labels returned from the connection.
    filterBy: LabelFilters

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Ordering options for labels returned from the connection.
    orderBy: LabelOrder
  ): LabelConnection!

  # Identifies when the lesson draft was last edited.
  lastEditedAt: Time!

  # The next lesson within this lesson's course, if any.
  nextLesson: Lesson

  # Identifies the lesson number.
  number: Int!

  # The previous lesson within this lesson's course, if any.
  previousLesson: Lesson

  # Identifies when the lesson was last published.
  publishedAt: Time!

  # The study associated with this lesson.
  study: Study!

  # Returns a list of events associated with the lesson.
  timeline(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Ordering options for events returned from the connection.
    orderBy: EventOrder
  ): LessonTimelineConnection!

  # The title of the lesson.
  title: String!

  # The HTTP path for this lesson.
  resourcePath: URI!

  # Identifies the date and time when the object was last updated.
  updatedAt: Time!

  # The HTTP URL for this lesson.
  url: URI!

  # Can the viewer enroll in this enrollable.
  viewerCanEnroll: Boolean!

  # Can the viewer update this lesson.
  viewerCanUpdate: Boolean!

  # Did the viewer author this lesson.
  viewerDidAuthor: Boolean!

  # The viewer's current working draft comment.
  viewerNewComment: LessonComment!
}

# An edge type for Lesson.
type LessonEdge implements Edge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Lesson
}

# A connection type for Lesson.
type LessonConnection implements Connection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [LessonEdge]

  # A list of nodes.
  nodes: [Lesson]

  # The total count of items in the connection.
  totalCount: Int!
}
