# Represents a lesson comment.
type LessonComment implements 
  Authorable,
  Deleteable,
  EventSourceable,
  Labelable,
  LessonTimelineItem,
  Node,
  StudyNode,
  UniformResourceLocatable,
  Updateable
{
  # The author of the comment.
  author: User

  # The body as Markdown.
  body: String!

  # The body rendered to HTML.
  bodyHTML: HTML!

  # The body rendered to text.
  bodyText: String!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # Returns a list of labels for the current lesson comment.
  labels(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first n elements form the list.
    first: Int

    # Returns the last n elements form the list.
    last: Int

    # Ordering options for labels returned from the connection.
    orderBy: LabelOrder
  ): LabelConnection!

  # The lesson associated with this comment.
  lesson: Lesson!

  # Identifies when the lesson comment was published at.
  publishedAt: Time

  # The HTTP path for this lesson comment.
  resourcePath: URI!

  # The study associated with this lesson comment.
  study: Study!

  # Identifies the date and time when the object was last updated.
  updatedAt: Time!

  # The HTTP URL for this lesson comment.
  url: URI!

  # Can the viewer delete this object.
  viewerCanDelete: Boolean!

  # Can the viewer update this object.
  viewerCanUpdate: Boolean!

  # Did the viewer author this comment.
  viewerDidAuthor: Boolean!
}

# An edge type for LessonComment.
type LessonCommentEdge implements Edge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: LessonComment
}

# A connection type for LessonComment.
type LessonCommentConnection implements Connection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [LessonCommentEdge]

  # A list of nodes.
  nodes: [LessonComment]

  # The total count of items in the connection.
  totalCount: Int!
}
