# Represents a password reset token.
type PRT implements Token {
  # Identifies the date and time when the token was issued.
  issuedAt: Time!

  # Identifies the date and time when the token expires.
  expiresAt: Time!

  # Identifies the date and time when the token ended.
  endedAt: Time
}
