# Represents a published event on a given subject.
type PublishedEvent implements 
  Node,
  StudyActivityEvent
{
  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The publishable associated with this `published` event.
  publishable: Publishable!

  # The study from which the event occurred.
  study: Study!

  # The user who performed the event.
  user: User!
}
