# An edge type for User.
type PupilEdge implements Edge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: User!

  # When was the item tutored?
  enrolledAt: Time!
}

# A connection type for User.
type PupilConnection implements Connection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [PupilEdge]

  # A list of nodes.
  nodes: [User]

  # The total count of items in the connection.
  totalCount: Int!
}
