# Represents a referenced event on a given subject.
type ReferencedEvent implements 
  LessonTimelineEvent,
  Node,
  UserAssetTimelineEvent
{
  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # Is this reference from a different study? 
  isCrossStudy: Boolean!

  # The source lesson of the event.
  source: Lesson!

  # The user who performed the event.
  user: User!
}
