# Represents a removed from activity event on a given subject.
type RemovedFromActivityEvent implements 
  UserAssetTimelineEvent,
  Node
{
  # The activity from which the asset was removed.
  activity: Activity!

  # The asset which was removed.
  asset: UserAsset!

  # Identifies the date and time when the object was created.
  createdAt: Time!

  id: ID!

  # The study from which the event occurred.
  study: Study!

  # The user who performed the event.
  user: User!
}
