# Return type for RemoveCourseLesson.
type RemoveCourseLessonPayload {
  # The course from which the lesson was removed.
  course: Course!

  # The ID of the lesson removed from the course.
  removedLessonId: ID!

  # The edge from the course study's lesson connection.
  removedLessonEdge: LessonEdge!
}
