# An edge in a topicable connection.
type TopicableEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Topicable

  # When was the item topiced in?
  topicedAt: Time!
}

# A list of topicables.
type TopicableConnection {
  # The number of courses associated with the topic.
  courseCount: Int!

  # A list of edges.
  edges: [TopicableEdge]

  # A list of nodes.
  nodes: [Topicable]

  # Information to aid in pagination.
  pageInfo: PageInfo!

  # The number of studies associated with the topic.
  studyCount: Int!
}
