# An edge type for UserTimelineEvent.
type UserTimelineEventEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The event at the end of the edge.
  node: UserTimelineEvent
}

# A connection type for UserTimelineEvent.
type UserTimelineConnection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [UserTimelineEventEdge]

  # A list of nodes.
  nodes: [UserTimelineEvent]

  # The total count of items in the connection.
  totalCount: Int!
}

# A connection type for UserTimelineEvent.
type UserReceivedTimelineConnection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [UserTimelineEventEdge]

  # A list of nodes.
  nodes: [UserTimelineEvent]

  # The total count of items in the connection.
  totalCount: Int!
}
