# Represents a user.
type UserAsset implements 
  Deleteable,
  Node,
  Searchable,
  StudyNode,
  UniformResourceLocatable,
  Updateable 
{
  # Identifies the date and time when the object was created.
  createdAt: Time!

  # Source url for use with hyperlinks.
  href: URI!

  id: ID!

  # The name of this asset.
  name: String!

  # The original name of this asset when uploaded.
  originalName: String!

  # The owner of this asset.
  owner: User!

  # Identifies the date and time when the object was published.
  publishedAt: Time

  # The HTTP path for this asset.
  resourcePath: URI!

  # The byte size of the asset.
  size: Int!

  # The study associated with this asset.
  study: Study!

  # The subtype of this asset.
  subtype: String!

  # The type of this asset.
  type: String!

  # Identifies the date and time when the object was last updated.
  updatedAt: Time!

  # The HTTP URL for this asset.
  url: URI!

  # Can the viewer delete this object?
  viewerCanDelete: Boolean!

  # Can the viewer update this object?
  viewerCanUpdate: Boolean!
}

# An edge type for UserAsset.
type UserAssetEdge implements Edge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: UserAsset
}

# A connection type for UserAsset.
type UserAssetConnection implements Connection {
  # Information to aid in pagination.
  pageInfo: PageInfo!

  # A list of edges.
  edges: [UserAssetEdge]

  # A list of nodes.
  nodes: [UserAsset]

  # The total count of items in the connection.
  totalCount: Int!
}
