# Represents a user.
type User implements Node, UniformResourceLocatable {
  # The user's public profile bio.
  bio: String

  # The user's public profile bio as HTML.
  bioHTML: HTML!

  # Identifies the date and time when the object was created.
  createdAt: Time

  # The user's public profile email.
  email: String

  id: ID!

  # Whether or not this user is a site administrator.
  isSiteAdmin: Boolean!

  # Whether or not this user is the viewing user.
  isViewer: Boolean!

  # The username used to login.
  login: String

  # The user's public profile name.
  name: String

  # The HTTP path for this user.
  resourcePath: URI!

  # Identifies the date and time when the object was last updated.
  updatedAt: Time

  # The HTTP URL for this user.
  url: URI!
}
